### ISSUE TITLE
写点UT

### ISSUE THREAD

**Issue by LKI** [LKI/meican#4]
不测试meican那边的接口
可以mock一些数据自己测测

**Comment by wyc902** [comment]
time flies. we do not use meican any more. 😄

**Comment by LKI** [comment]
@wyc902 Microsoft now use other dinner vendor?

**Comment by wyc902** [comment]
哈？不是不是，we指的是神通我们。我开个玩笑的。看你17年开个issue，但是好像我离开的时候用西乡了美餐都不怎么用了似乎。纯属开玩笑哈~~

**Comment by LKI** [comment]
@wyc902 确实…现在我们也不用美餐了，这个项目得整顿一下
